---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  annotations: {}
  name: "my-prometheus-prometheus-pushgateway"
  labels:
    helm.sh/chart: "prometheus-pushgateway-2.0.2"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "prometheus-pushgateway"
    app.kubernetes.io/instance: "my-prometheus"
    app.kubernetes.io/version: "v1.5.1"

---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    prometheus.io/probe: "pushgateway"
  name: "my-prometheus-prometheus-pushgateway"
  labels:
    helm.sh/chart: "prometheus-pushgateway-2.0.2"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "prometheus-pushgateway"
    app.kubernetes.io/instance: "my-prometheus"
    app.kubernetes.io/version: "v1.5.1"
spec:
  externalIPs: []
  loadBalancerSourceRanges: []
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "prometheus-pushgateway"
    app.kubernetes.io/instance: "my-prometheus"
  ports:
  - name: "http"
    port: 9091
    protocol: "TCP"
    targetPort: 9091

---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations: {}
  name: "my-prometheus-prometheus-pushgateway"
  labels:
    helm.sh/chart: "prometheus-pushgateway-2.0.2"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/name: "prometheus-pushgateway"
    app.kubernetes.io/instance: "my-prometheus"
    app.kubernetes.io/version: "v1.5.1"
    app.kubernetes.io/component: "deployment.my-prometheus-prometheus-pushgateway"
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: "prometheus-pushgateway"
      app.kubernetes.io/instance: "my-prometheus"
    matchExpressions: []
  strategy:
    type: "Recreate"
  template:
    metadata:
      annotations: {}
      labels:
        helm.sh/chart: "prometheus-pushgateway-2.0.2"
        app.kubernetes.io/managed-by: "Helm"
        app.kubernetes.io/name: "prometheus-pushgateway"
        app.kubernetes.io/instance: "my-prometheus"
        app.kubernetes.io/version: "v1.5.1"
        app.kubernetes.io/component: "deployment.my-prometheus-prometheus-pushgateway"
    spec:
      terminationGracePeriodSeconds: 30
      nodeSelector: {}
      serviceAccountName: "my-prometheus-prometheus-pushgateway"
      volumes:
      - name: "storage-volume"
        emptyDir: {}
      containers:
      - name: "pushgateway"
        image: "prom/pushgateway:v1.5.1"
        command: []
        args: []
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: "metrics"
          containerPort: 9091
          protocol: "TCP"
        volumeMounts:
        - name: "storage-volume"
          mountPath: "/data"
          subPath: ""
        livenessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: "/-/ready"
            port: 9091
        readinessProbe:
          initialDelaySeconds: 10
          timeoutSeconds: 10
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            path: "/-/ready"
            port: 9091
      securityContext:
        runAsUser: 65534
        runAsNonRoot: true
        fsGroup: 65534
        supplementalGroups: []
